### ISSUE TITLE
Cant run on Windows

### ISSUE THREAD

**Issue by ahmadrasyidsalim** [rollup/rollupjs.org#193]
I trying to build the website on my local, I found this.

- OS Name: Microsoft Windows
- Version: 10.0.18362 Build 18362

![image](https://user-images.githubusercontent.com/18344132/66118082-b81f7000-e5ff-11e9-9179-f7c43b2ab097.png)

**Comment by Jeel5000** [comment]
I'm having the same issue. I guess it's occurring because of the internal server error. 
here is the logs. 
```
src\routes\guide\[lang]\index.svelte changed. Rebuilding...

[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.     

- totalist


[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.     

- totalist

✔ server (9.0s)
✔ client (9.0s)
✔ service worker (250ms)
TypeError: Cannot read properties of null (reading '1')
    at C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:723:29
    at Array.map (<anonymous>)
    at create_guide (C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:719:15)
    at createGuide (C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:708:37)
    at get$1 (C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:814:20)
    at C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:2737:27
    at Generator.next (<anonymous>)
    at C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:2587:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ZEEL\Documents\languages\web\projects\rollupjs.org\__sapper__\dev\server\server.js:2583:12)
```

![image](https://user-images.githubusercontent.com/63534268/180606977-e6f86b03-bc01-45d0-99d5-c7d96e64d75a.png)
