### ISSUE TITLE
Error when running `npm start`

### ISSUE THREAD

**Issue by mattmazzola** [rollup/rollupjs.org#39]
npm: 2.15.5
node: 4.2.1

I was in the process of submitting a pull request and wanted to verify my changes before submitting, but I received an error when attempting to run `npm start`.

Output:

```
λ npm start

> rollupjs.org@0.1.0 start C:\Users\MattMazzola\Source\Repos\rollupjs.org
> gobble

gobble: server listening on port 4567
gobble: livereload server running
gobble: 01-replace done in 202ms
∙∙∙∙∙∙∙ 02-unknown running...
gobble: 02-unknown transformation failed

input:  C:\Users\MattMazzola\Source\Repos\rollupjs.org\src\guide
output: C:\Users\MattMazzola\Source\Repos\rollupjs.org\.gobble\02-unknown\1
>>>
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at C:\Users\MattMazzola\Source\Repos\rollupjs.org\gobblefile.js:36:29
    at Array.map (native)
    at Object.<anonymous> (C:\Users\MattMazzola\Source\Repos\rollupjs.org\gobblefile.js:32:6)
    at Object.fn (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble\dist\gobble.js:1958:41)
    at Queue.queue._run (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble\dist\gobble.js:72:10)
    at Queue.add (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble\dist\gobble.js:101:9)
    at C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble\dist\gobble.js:1909:19
    at lib$es6$promise$$internal$$tryCatch (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble-postcss\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble-postcss\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble-postcss\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (C:\Users\MattMazzola\Source\Repos\rollupjs.org\node_modules\gobble-postcss\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:125:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
<<<
```

Do you know any workarounds?

**Comment by Rich-Harris** [comment]
Sorry for never getting back to you on this. The repo has a completely new build process now — details on the README — so I'll close this issue.
