### ISSUE TITLE
thicker/darker font?

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#85]
Because font rendering on Windows is *so shit*, the site is apparently quite hard to read (screenshot from Gitter):

![screen](https://user-images.githubusercontent.com/1162160/30162602-64b46138-93a3-11e7-8d9a-2838500acb0f.png)

**Comment by GrosSacASac** [comment]
Please increase the font weight to 500 or change the font

**Comment by GrosSacASac** [comment]
Someone told me it was hard to read

**Comment by lukastaegert** [comment]
PR welcome

**Comment by GrosSacASac** [comment]
Another error happened
 npm run dev

> rollupjs.org@1.0.0 dev C:\Users\Sac\Documents\GitHub\rollupjs.org
> sapper dev

✔ server (4.7s)
✔ client (4.7s)
✔ service worker (44ms)
C:\Users\Sac\Documents\GitHub\rollupjs.org\__sapper__\dev\server\server.js:48
                const front_matter = match[1];
                                          ^

TypeError: Cannot read property '1' of null
    at C:\Users\Sac\Documents\GitHub\rollupjs.org\__sapper__\dev\server\server.js:48:29
    at Array.map (<anonymous>)
    at create_guide (C:\Users\Sac\Documents\GitHub\rollupjs.org\__sapper__\dev\server\server.js:44:15)
    at C:\Users\Sac\Documents\GitHub\rollupjs.org\__sapper__\dev\server\server.js:35:14
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\Users\Sac\Documents\GitHub\rollupjs.org\__sapper__\dev\server\server.js:32:3)       
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

**Comment by GrosSacASac** [comment]
https://github.com/rollup/rollupjs.org/pull/196

**Comment by lukastaegert** [comment]
Fixed
